# frontend/Dockerfile.dev
FROM node:24
WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ENV VITE_HOST=0.0.0.0
ENV VITE_PORT=5173

EXPOSE 5173

CMD ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0 --port 5173"]
