name: Frontend CI/CD

permissions:
  contents: read
  actions: write

on:
  push:
    branches: [ master ]

jobs:
  frontend-ci-cd:
    uses: ftpreavis/.github/.github/workflows/frontend-ci-cd.yml@master
    secrets: inherit
