name: Frontend CI/CD

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  actions: write

# Targets ci-cd template
jobs:
  frontend-ci-cd:
    uses: ftpreavis/.github/.github/workflows/frontend-ci-cd.yml@master
    secrets: inherit
